### PR TITLE
DAX Patterns Chp 2 measures

### PR DESCRIPTION
**Pull request by kevarnold972**
Created additional measures based upon DAX Patterns chapter 2

Created 2 PowerShell scripts to assist with development. One renames the file from the GUID to the template name. The other generates the readme.md file for each directory.

### CODE REVIEW

**Comment by MikeCarlo** [comment]
What the heck, This update Blows my mind!! Wonderful Script in the Utilities area.

**Comment by MikeCarlo** [comment]
I think it would be helpful to add a little documentation to the Repo readme.md to explain how to us the powershell utility. maybe you could add that in a future update.

**Comment by didierterrien** [comment]
Thank you Kevin for this great contribution!

**Comment by didierterrien** [comment]
I suggest  to add  authors in the Readme because it can be a search criteria. 
It would be valuable to have the same Readme file at the top level so we can search in one file.
Thanks again

**Pull request merged**
